easy_admin:
  site_name: 'NNIZER'
  user:
    name_property_path: 'name'
    display_avatar: true

  list:
    title: 'List of %%entity_label%%'
    actions:
      - { name: edit, icon: pencil, label: Edit }
      - { name: delete, icon: exclamation, label: Delete }
      - { name: search, label: Search }
      - { name: new, icon: plus, label: Add new  }

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - 'id'
          - 'email'
          - 'roles'
          - 'name'
          - 'createdAt'
      form:
        fields:
          - 'email'
          - 'name'
          - { property: 'plainPassword', type: 'text', label: 'New password' }
    Contractor:
      class: App\Entity\Contractor
      list:
        fields:
          - 'id'
          - 'firstname'
          - 'lastname'
          - 'username'
          - 'email'
          - 'reservations'
          - 'settings'
          - 'reviews'
          - 'coverPhoto'
          - 'profilePhoto'
      form:
        fields:
          - 'firstname'
          - 'lastname'
          - 'username'
          - 'email'
          - 'phoneNumber'
          - 'isVerified'
          - 'title'
          - 'address'
          - 'facebook'
          - 'description'
          - { property: 'plainPassword', type: 'text', label: 'New password' }
    ContractorSettings:
      class: App\Entity\ContractorSettings
    Reservation:
      class: App\Entity\Reservation
    Rewiev:
      class: App\Entity\Review
