easy_admin:
  site_name: 'NNIZER'
  user:
    name_property_path: 'name'
    display_avatar: true

  list:
    title: 'List of %%entity_label%%'
    actions:
      - { name: edit, icon: pencil, label: Edit }
      - { name: delete, icon: exclamation, label: Delete }
      - { name: search, label: Search }
      - { name: new, icon: plus, label: Add new  }

  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - 'id'
          - 'email'
          - 'roles'
          - 'name'
          - 'createdAt'
#          - { property: 'password', label: 'Password hash' }
    Contractor:
      class: App\Entity\Contractor
      list:
        fields:
          - 'id'
          - 'username'
          - { property: 'roles' }
          - { property: 'password', label: 'Password hash' }
    ContractorSettings:
      class: App\Entity\ContractorSettings
    Reservation:
      class: App\Entity\Reservation
    Rewiev:
      class: App\Entity\Review
