vich_uploader:
    db_driver: orm

    mappings:
        contractorsProfile:
            uri_prefix: '%profile_images%'
            upload_destination: '%kernel.project_dir%/public%profile_images%'
        contractorsCover:
            uri_prefix: '%cover_images%'
            upload_destination: '%kernel.project_dir%/public%cover_images%'
