vich_uploader:
    db_driver: orm

    mappings:
        contractorsProfile:
            uri_prefix: /uploads/profile
            upload_destination: '%kernel.project_dir%/public/uploads/profile'
        contractorsCover:
            uri_prefix: /uploads/cover
            upload_destination: '%kernel.project_dir%/public/uploads/cover'
